[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data5310_final_project_2025"
version = "0.1.0"
requires-python = ">=3.10, <3.13"

dependencies = [
    "notebook",
    "pandas",
    "geopandas",
    "altair"
]